### ISSUE TITLE
List and short description of the xk6-nats APIs

### ISSUE THREAD

**Issue by ppcano** [ydarias/xk6-nats#1]
@ydarias, it could help to document the list of APIs on this extension. An example [here](https://k6.io/blog/load-test-your-kafka-producers-and-consumers-using-k6/).

<img width="826" alt="Screenshot 2021-11-19 at 10 06 43" src="https://user-images.githubusercontent.com/825430/142596256-f5446eea-9e67-4a8b-97f5-648a565e7e48.png">

**Comment by ydarias** [comment]
Thank you @ppcano 

You are completely right 👏  I will add it to the readme file.
